### ISSUE TITLE
Bug: modcc referencing a non-existent procedure causes modcc segfault

### ISSUE THREAD

**Issue by halfflat** [eth-cscs/nestmc-proto#92]
Example: modified `pas.mod` with:
```
BREAKPOINT {
    nosuchproc()
    i = g*(v - e)
}
```

Running modcc on this gives a segmentation fault. Stack trace from gdb:
```
CallExpression::semantic (this=0x7e55e0, scp=...) at .../modcc/expression.cpp:374
374	    if(s->kind()==symbolKind::local_variable || s->kind()==symbolKind::variable) {
(gdb) bt
#0  CallExpression::semantic (this=0x7e55e0, scp=...) at .../modcc/expression.cpp:374
#1  0x00000000004c6829 in BlockExpression::semantic (this=<optimized out>, scp=...) at .../modcc/expression.cpp:746
#2  0x00000000004c1f30 in ProcedureExpression::semantic (this=<optimized out>, global_symbols=...) at .../modcc/expression.cpp:454
#3  0x00000000004afe57 in Module::semantic (this=<optimized out>) at .../modcc/module.cpp:163
#4  0x0000000000472cf3 in main (argc=<optimized out>, argv=<optimized out>) at .../modcc/modcc.cpp:129
```

**Comment by vkarak** [comment]
I think this is duplicate of #27.

**Comment by halfflat** [comment]
It totally is! My mistake. I'll close this one.
